In [32]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

In [36]:
import nltk
nltk.download('punkt')
print("'punkt' resource downloaded.")

'punkt' resource downloaded.


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [37]:
nltk.download('wordnet')
print("'wordnet' resource downloaded.")

'wordnet' resource downloaded.


[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [38]:
nltk.download('punkt_tab')
print("'punkt_tab' resource downloaded.")

'punkt_tab' resource downloaded.


[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


In [39]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

# Initialize the lemmatizer
lemmatizer = WordNetLemmatizer()

# Define a custom tokenizer function that includes lemmatization
def custom_tokenizer_with_lemmatization(text):
    # Tokenize the text, convert to lowercase, and lemmatize each token
    tokens = word_tokenize(text.lower())
    lemmatized_tokens = [lemmatizer.lemmatize(t) for t in tokens]
    return lemmatized_tokens

# Initialize CountVectorizer with ngram_range and the custom tokenizer
# Note: When using a custom tokenizer, ngram_range will apply to the tokens returned by the tokenizer.
count_bigrams = CountVectorizer(ngram_range=(1, 2), tokenizer=custom_tokenizer_with_lemmatization)
docs = np.array([
    'The sun is shining',
    'The weather is sweet',
    'The sun is shining, the weather is sweet, and one and one is two'])

# Fit and transform the documents
bag_bigrams = count_bigrams.fit_transform(docs)

print("Vocabulary with bigrams (using custom tokenizer with lemmatization):")
print(count_bigrams.vocabulary_)
print("\nBag of words with bigrams (using custom tokenizer with lemmatization):")
print(bag_bigrams.toarray())

Vocabulary with bigrams (using custom tokenizer with lemmatization):
{'the': 18, 'sun': 14, 'is': 5, 'shining': 12, 'the sun': 19, 'sun is': 15, 'is shining': 6, 'weather': 22, 'sweet': 16, 'the weather': 20, 'weather is': 23, 'is sweet': 7, ',': 0, 'and': 3, 'one': 9, 'two': 21, 'shining ,': 13, ', the': 2, 'sweet ,': 17, ', and': 1, 'and one': 4, 'one and': 10, 'one is': 11, 'is two': 8}

Bag of words with bigrams (using custom tokenizer with lemmatization):
[[0 0 0 0 0 1 1 0 0 0 0 0 1 0 1 1 0 0 1 1 0 0 0 0]
 [0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 1]
 [2 1 1 2 2 3 1 1 1 2 1 1 1 1 1 1 1 1 2 1 1 1 1 1]]


In [40]:
count_bigrams.vocabulary_

{'the': 18,
 'sun': 14,
 'is': 5,
 'shining': 12,
 'the sun': 19,
 'sun is': 15,
 'is shining': 6,
 'weather': 22,
 'sweet': 16,
 'the weather': 20,
 'weather is': 23,
 'is sweet': 7,
 ',': 0,
 'and': 3,
 'one': 9,
 'two': 21,
 'shining ,': 13,
 ', the': 2,
 'sweet ,': 17,
 ', and': 1,
 'and one': 4,
 'one and': 10,
 'one is': 11,
 'is two': 8}

In [41]:
print(bag_bigrams.toarray())

[[0 0 0 0 0 1 1 0 0 0 0 0 1 0 1 1 0 0 1 1 0 0 0 0]
 [0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 1]
 [2 1 1 2 2 3 1 1 1 2 1 1 1 1 1 1 1 1 2 1 1 1 1 1]]


In [42]:
from sklearn.linear_model import LogisticRegression
import numpy as np

# X is the bag_bigrams generated from the documents
X = bag_bigrams.toarray()

# Define the target variable y
y = np.array([1, 1, 0])

# Initialize and train a Logistic Regression model
model = LogisticRegression(solver='liblinear', random_state=0)
model.fit(X, y)

print("Logistic Regression Model trained successfully.")
print(f"Model coefficients: {model.coef_}")
print(f"Model intercept: {model.intercept_}")

# Predict on the training data to show how it works
predictions = model.predict(X)
print(f"\nPredictions on training data: {predictions}")
print(f"Actual target values: {y}")

Logistic Regression Model trained successfully.
Model coefficients: [[-0.3015964  -0.1507982  -0.1507982  -0.3015964  -0.3015964   0.04851078
   0.09965449  0.09965449 -0.1507982  -0.3015964  -0.1507982  -0.1507982
   0.09965449 -0.1507982   0.09965449  0.09965449  0.09965449 -0.1507982
   0.19930898  0.09965449  0.09965449 -0.1507982   0.09965449  0.09965449]]
Model intercept: [0.35010718]

Predictions on training data: [1 1 0]
Actual target values: [1 1 0]
